site_name: FGA/Klinika

repo_name: "08_Klinika"
repo_url: "https://github.com/ResidenciaTICBrisa/08_Klinika"

theme:
  name: material
  features:
   - content.code.copy
  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Trocar para o modo escuro

    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Trocar para o modo claro



markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Consultas a inteligência artificial por comando de voz: index.md
