site_name: FGA/Klinika

repo_name: "08_Klinika"
repo_url: "https://github.com/ResidenciaTICBrisa/08_Klinika"

theme:
  name: material
  logo: assets/klinika.svg
  favicon: assets/klinika.svg
  features:
   - content.code.copy
  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Trocar para o modo escuro

    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Trocar para o modo claro

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Entregas: 
    - Entrega 1:
      - Web Klinika: ./entregas/entrega1/entregas1_web.md
      - Klinika Admin: ./entregas/entrega1/entregas1_admin.md
    - Entrega 2:
      - Web Klinika: ./entregas/entrega2/entregas2_web.md
      - Klinika Admin: ./entregas/entrega2/entregas2_admin.md
  - Modelo transcrição áudio: transcribeAudio.md
  - Scrum: ./scrum.md
  - Atas:
    - Resumo: ./atas/resumo.md
    - 23/06/2023: ./atas/ata_23_06.md
    - 26/06/2023: ./atas/ata_26_06.md
    - 31/07/2023: ./atas/ata_31_07.md
    - 02/08/2023: ./atas/ata_02_08.md
    - 09/08/2023: ./atas/ata_09_08.md
    - 14/08/2023: ./atas/ata_14_08.md
    - 18/08/2023: ./atas/ata_18_08.md
    - 21/08/2023: ./atas/ata_21_08.md
    - 23/08/2023: ./atas/ata_23_08.md
    - 30/08/2023: ./atas/ata_30_08.md
    - 04/09/2023: ./atas/ata_04_09.md
    - 06/09/2023: ./atas/ata_06_09.md
    - 11/09/2023: ./atas/ata_11_09.md
    - 18/09/2023: ./atas/ata_18_09.md
    - 25/09/2023: ./atas/ata_25_09.md